In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr = arr + 2
print(arr)

arr = arr * 3
print(arr)

arr = arr / 2
print(arr)

[3 4 5 6 7]
[ 9 12 15 18 21]
[ 4.5  6.   7.5  9.  10.5]


In [2]:
arr=np.flip(arr)
print(arr)

[10.5  9.   7.5  6.   4.5]


In [3]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

values,counts=np.unique(x,return_counts=True)

max_count=np.max(counts)

most_freq=values[counts==max_count]

print("Most frequent element is ",most_freq)

for val in most_freq:
  print("Indices ",np.where(x==val)[0])

Most frequent element is  [1]
Indices  [0 5 7 8 9]


In [7]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

most_count = np.max(counts)
most_freq = values[counts == most_count]

print("Most frequent element(s):", most_freq)

for val in most_freq:
    print("Indices:", np.where(y == val)[0])

Most frequent element(s): [1 3]
Indices: [0 1 2]
Indices: [4 8 9]


In [9]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0][1])
print(arr[2][0])

20
70


In [11]:
sahu=np.linspace(10,100,25)
print("array ",sahu)
print("dimensions ",sahu.ndim)
print("shape ",sahu.shape)
print("total elements ",sahu.size)
print("Data type : ", sahu.dtype)
print("Total Bytes : ",sahu.nbytes)

print("using reshape")
print(sahu.reshape(1,25))

print("using T")
print(sahu.reshape(1,25).T)

array  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimensions  1
shape  (25,)
total elements  25
Data type :  float64
Total Bytes :  200
using reshape
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
using T
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [13]:
ucs420_sahu=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90],
    [15,20,35]
])
print("original matrix")
print(ucs420_sahu)

print("mean ",np.mean(ucs420_sahu))
print("Median ",np.median(ucs420_sahu))
print("Max ",np.max(ucs420_sahu))
print("Min ",np.min(ucs420_sahu))
print("Unique elements ",np.unique(ucs420_sahu))

reshaped_ucs420_sahu=ucs420_sahu.reshape(4,3)
print(reshaped_ucs420_sahu)

resize_ucs420_sahu=np.resize(ucs420_sahu,(2,3))
print(resize_ucs420_sahu)


original matrix
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
mean  43.333333333333336
Median  37.5
Max  90
Min  10
Unique elements  [10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
