In [3]:
import numpy as np
temp = np.array([25, 28, 31, 35, 38, 27, 33, 40])
print(temp)
temp=temp+2
print(temp)
far=(9*temp)/5+32
print(far)
greater32=temp[temp>32]
print(greater32)
count=np.sum(temp>32)
print(count)

[25 28 31 35 38 27 33 40]
[27 30 33 37 40 29 35 42]
[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
[33 37 40 35 42]
5


In [8]:
step = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

total_step=np.sum(step)
print(total_step)
mean_step=np.mean(step)
print(mean_step)
max_step=np.max(step)
min_step=np.min(step)
print(max_step)
print(min_step)
total_step_day=np.sum(step,axis=0)
total_step_user=np.sum(step,axis=1)
print(total_step_day)
print(total_step_user)
position = np.unravel_index(np.argmax(step), step.shape)
print(position)

84200
7016.666666666667
9500
4500
[26500 27300 30400]
[18300 24500 14400 27000]
(np.int64(3), np.int64(2))


In [19]:
original = np.array([1, 2, 3, 4, 5, 6])
subset = original[1:4]
subset[0] = 999

print(subset)
print(original)

copy=original[1:4].copy()
copy[0]=500
print(copy)
print(original)

matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)
print("First row:", matrix[0, :])
print("Last row:", matrix[-1, :])
print("Second column:", matrix[:, 1])
print("Rows 1-2, columns 2-3:", matrix[0:2, 1:3])

flat_array = matrix.flatten()
ravel_array = matrix.ravel()

print("Flatten:", flat_array)
print("Ravel:", ravel_array)

ravel_array[0] = 999
print(matrix)

flat_array[0]=1000
print(matrix)

shp=np.array()
print(np.shape(matrix))
print(np.ndim(matrix))
print(np.size(matrix))
print(matrix.dtype)

[999   3   4]
[  1 999   3   4   5   6]
[500   3   4]
[  1 999   3   4   5   6]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2, columns 2-3: [[2 3]
 [6 7]]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
[[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print(X.shape)
print(X.ndim)
XT=X.T
print(XT)
XT_X = X.T @ X
print(XT_X)

inverse = np.linalg.inv(XT_X)
print(inverse)

beta = inverse @ X.T @ y


print("Sleep:", beta[0])
print("Activity:", beta[1])
print("Stress:", beta[2])


new_user = np.array([5, 40, 7])
prediction = new_user @ beta

print("Q4(g) Predicted assistance score:", prediction)